from anthropic import Anthropic
import anthropic.types
import os

class AnthropicClient:
    def __init__(self, verbose=False):
        """Initialize the Anthropic client with the API key."""
        self.client = Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))
        self.verbose = verbose

    def stream_completion(self, messages, model, max_tokens=1000, **kwargs):
        """Stream completion from the Anthropic API.

        Args:
            messages (list): List of messages.
            model (str): Model for completion.
            max_tokens (int): Maximum number of tokens to generate.
            **kwargs: Additional keyword arguments.

        Yields:
            str: Text generated by the Anthropic API.
        """
        # Extract system message if present, otherwise set to None
        system_messages = [message['content'] for message in messages if message['role'] == 'system']
        system_message = system_messages[0] if system_messages else None
        
        # Filter out system messages from the messages list
        messages = [message for message in messages if message['role'] != 'system']

        try:
            # Prepare the arguments for the Anthropic API call
            api_args = {
                "model": model,
                "messages": messages,
                "max_tokens": max_tokens,
                **kwargs
            }
            
            # Only include the system parameter if a system message is present
            if system_message:
                api_args["system"] = system_message

            # Stream the completion
            with self.client.messages.stream(**api_args) as stream:
                for event in stream:
                    if isinstance(event, anthropic.types.MessageStartEvent):
                        continue
                    if isinstance(event, anthropic.types.ContentBlockStartEvent):
                        continue
                    if isinstance(event, anthropic.types.ContentBlockDeltaEvent):
                        yield event.delta.text
        except Exception as e:
            if self.verbose:
                import traceback
                traceback.print_exc()
            else:
                print(f"An error occurred streaming completion from Anthropic API: {e}")
            raise RuntimeError(f"An error occurred streaming completion from Anthropic API: {e}")
        
        
# Test the AnthropicClient
if __name__ == "__main__":
    client = AnthropicClient(verbose=True)
    messages = [
        {
            "role": "system",
            "content": "Be precise and concise."
        },
        {
            "role": "user",
            "content": "What is the capital of France?"
        }
    ]
    model = "claude-3-5-sonnet-20240620"

    print("Response:")
    for chunk in client.stream_completion(messages, model, max_tokens=100):
        print(chunk, end='', flush=True)
    print()  # Add a newline at the end
