import os
from portkey_ai import Portkey
from dotenv import load_dotenv

class PortkeyClient:
    """Client for interacting with the Portkey API for chat completions and other functionalities."""
    def __init__(self, verbose=False):
        """
        Initialize the PortkeyClient with the API key.
        
        Args:
            verbose (bool): Whether to print verbose output.
        """
        
        self.client = Portkey(
            api_key=os.getenv('PORTKEY_API_KEY'),
            virtual_key=os.getenv('PORTKEY_VIRTUAL_KEY')
        )
        self.verbose = verbose

    def stream_completion(self, messages, model, **kwargs):
        """
        Get chat completions from the Portkey API.

        Args:
            messages (list): List of messages used as context or prompt. Each message should be a dict with 'role' and 'content'.
            model (str): Model identifier for text generation.
            **kwargs: Additional keyword arguments for the API request.

        Yields:
            str: Text generated by the Portkey API in response to the messages.
        """
        try:
            completion = self.client.chat.completions.create(
                messages=messages,
                model=model,
                stream=True,
                **kwargs
            )
            for chunk in completion:
                content = chunk.choices[0].delta.content
                if content is not None:
                    yield content
        except Exception as e:
            if self.verbose:
                import traceback
                traceback.print_exc()
            else:
                print(f"An error occurred while getting completions from Portkey API: {e}")
            raise RuntimeError(f"An error occurred while getting completions from Portkey API: {e}")

# Example of using the PortkeyClient
if __name__ == "__main__":
    load_dotenv()  # Move this here to ensure environment variables are loaded
    portkey_client = PortkeyClient(verbose=True)
    messages = [
        {"role": "user", "content": "Explain the importance of fast language models"}
    ]
    for response in portkey_client.stream_completion(messages, model=os.getenv('PORTKEY_MODEL')):
        print(response, end="", flush=True)
    print()  # Add a newline at the end
