import os
from portkey_ai import Portkey
from dotenv import load_dotenv

class PortkeyPromptClient:
    """Client for interacting with the Portkey API for chat completions."""
    def __init__(self, verbose=False):
        """
        Initialize the PortkeyPromptClient with the API key.
        
        Args:
            verbose (bool): Whether to print verbose output.
        """
        self.client = Portkey(
            api_key=os.getenv('PORTKEY_API_KEY')
        )
        self.prompt_id = os.getenv('PORTKEY_PROMPT_ID')
        self.verbose = verbose

    def stream_completion(self, messages, model=None, **kwargs):
        """
        Get streaming prompt completions from the Portkey API.

        Args:
            messages (list): List of message dictionaries.
            model (str, optional): The model to use for completion. Ignored for Portkey.
            **kwargs: Additional keyword arguments for the API request.

        Yields:
            str: Text generated by the Portkey API in response to the prompt.
        """
        try:
            # Filter out system messages, since these are set in the Portkey prompt profile.
            filtered_messages = [msg for msg in messages if msg['role'] != 'system']
            
            completion = self.client.prompts.completions.create(
                prompt_id=self.prompt_id,
                variables={
                    "chat_history": filtered_messages
                },
                stream=True,
                **kwargs
            )
            for chunk in completion:
                content = chunk.choices[0].delta.content
                if content is not None:
                    yield content
        except Exception as e:
            if self.verbose:
                import traceback
                traceback.print_exc()
            else:
                print(f"An error occurred while getting completions from Portkey API: {e}")
            raise RuntimeError(
                f"An error occurred while getting completions from Portkey API: {e}"
            )

# Example of using the PortkeyPromptClient. No System prompt is needed, as this is set in the Portkey prompt profile.
if __name__ == "__main__":
    load_dotenv()  # Move this here to ensure environment variables are loaded
    portkey_client = PortkeyPromptClient(verbose=True)
    prompt_id = os.getenv('PORTKEY_PROMPT_ID')
    messages = [
    {
        "content": "How can I help you today",
        "role": "assistant"
    },
    {
        "content": "What is the weather like today?",
        "role": "user"
    }
    ]
    for response in portkey_client.stream_completion(messages, model=os.getenv('PORTKEY_MODEL')):
        print(response, end="", flush=True)
    print()  # Add a newline at the end
